version: '3'

services:
    http-server.magento2:
      image: nginx:1.13.0
      volumes:
        - ./www/:/var/application/www
        - ./nginx-custom/nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - worker.magento2

    worker.magento2:
      build: php-fpm-custom
      working_dir: /var/application
      command: sh ./start-up.sh ;
      volumes:
        - ./:/var/application
        - ./php-fpm-custom/php.ini:/usr/local/etc/php/php.ini
        - /etc/hosts:/etc/hosthosts
      env_file:
        - ./install-magento.env
      links:
        - db.magento2

    db.magento2:
      image: mariadb:10.1
      env_file:
        - ./mariadb-custom/setup.env
